---

dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: alma9-lego
    image: "ghcr.io/almalinux/9-init"
    pre_build_image: true
    tty: false
    command: "/sbin/init"
    systemd: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    groups: ["el", "el9"]
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        lego_deploy_hooks:
          - name: sudo-restart-nginx
            content: |
              #!/bin/sh
              systemctl restart nginx

        lego_certificates:
          example:
            challenge: example
            account: main
            domains: ["example.com", "*.example.com"]

        lego_challenges:
          example:
            dns:
              provider: "rfc2136"
              envFile: "/etc/lego/env.d/example"

        lego_accounts:
          main:
            email: "you@example.com"
            acceptsTermsOfService: true

        lego_env:
          example:
            RFC2136_NAMESERVER: 127.0.0.1
            RFC2136_TSIG_KEY: lego
            RFC2136_TSIG_ALGORITHM: hmac-sha256.
            RFC2136_TSIG_SECRET: YWJjZGVmZGdoaWprbG1ub3BxcnN0dXZ3eHl6MTIzNDU=
verifier:
  name: ansible
